[package]
name = "chive"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
fuser = "0.15.1"
serde = { version = "1.0.217", features = ["derive"] }
time = "0.3.37"
toml = "0.8.19"
